version: '3.1'
services:
  #   db:
  #     image: mysql
  #     # restart: always
  #     environment:
  #       MYSQL_ROOT_PASSWORD: root
  #       MYSQL_DATABASE: test_db
  #     ports:
  #       - "3307:3306"
  #     volumes:
  #       - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql


  database:
    image: mysql
    ports:
      - "33061:3306"
    # command: --init-file /data/application/init.sql
    # volumes:
    #     - ./init.sql:/data/application/init.sql
    volumes:
      - ./data/mysql:/var/lib/mysql
      # - ./data/mysql_config:/etc/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test


    